/// @desc	Errors generated by the LDtk Loader will throw exceptions as
///	LDtkErrors, which can be handled or will cause GM to crash with an error
///	message.  The specific error can be checked against code and the LDtkException
///	enumerator.
function LDtkError( _code, _message ) constructor {
	static toString	= function() {
		return "\n\n\n" + message + "\n\n\n";
		
	}
	var _i = 2; repeat( argument_count - 2 ) {
		_message	= string_replace( _message, "%", argument[ _i++ ] );
		
	}
	message	= "LDtk Error: " + _message;
	code	= _code;
	
}
enum LDtkException {
	FileNotFound, FileAccessFailed, BadJSONFormat, BadLDtkFormat
	
}
